### ISSUE TITLE
Compile error & solution in VS 2013

### ISSUE THREAD

**Issue by koscianski** [paroj/artoolkitplus#1]
In file "rppMultiGetTransMat.cpp",
replace line
                marker_id_freq.insert(std::make_pair < int,int > (int(m_patt_id), 1));
with
                marker_id_freq.insert(std::make_pair(int(m_patt_id), 1));
do the same with the line
           m2c_idx.insert(std::make_pair(int(m), int((*c_iter).first)));

**Comment by paroj** [comment]
thanks. can you make a pull request for this?
